<?php

namespace Sensio\Bundle\HangmanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function getMostRecentPlayers($limit)
    {
        $q = $this
            ->createQueryBuilder('p')
            ->select('p.id, p.username')
            ->where('p.isActive = :active')
            ->orderBy('p.id','DESC')
            ->setMaxResults($limit)
            ->SetParameter('active', true)
            ->getQuery()
        ;

        return $q->getResult();
    }
}